### ISSUE TITLE
Statikus analízis

### ISSUE THREAD

**Issue by adetrux** [BME-MIT-IET/chillisbab-iet-2019#1]
Statikus analízis eszköz futtatása és jelzett hibák átnézése (SonarQube)

**Comment by adetrux** [comment]
Egyik kritikus hiba egy lehetséges megjavítása: lockObject használata this helyett
commit: efeab1214d8b3b403f4dbe429302636bdc4c9e71

**Comment by krumplipucolo** [comment]
Két jelentős hiba javítása: két külön fájlban 2-2 if elágazás egyesítése a könnyebb olvashatóság miatt.
első commit: 96093a2
második commit: ec90759

**Comment by adamtorok96** [comment]
Sérülékenységi hibák javítása ebben a PR-ban: https://github.com/BME-MIT-IET/chillisbab-iet-2019/pull/4
Bug-ok javítása ebben a PR-ban: https://github.com/BME-MIT-IET/chillisbab-iet-2019/pull/5
